package org.hms.hostelmaintanancesystem.user;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Spring Data JPA Repository for User entity.
 *
 * Extending JpaRepository<User, Long> gives us:
 *   - save(User), findById(Long), findAll(), deleteById(Long)
 *   - count(), existsById(Long)
 *   - Pagination: findAll(Pageable)
 *
 * Custom Query Method:
 *   findByEmail(String email) -> auto-generated by Spring Data JPA
 *
 * @Repository        -> Marks this as a Spring Bean. Optional on interfaces
 *                         extending JpaRepository (Spring adds it automatically),
 *                         but explicit is clearer.
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    /**
     * Finds a user by their email address.
     *
     * Used for:
     *   - Login authentication (Phase 4)
     *   - Duplicate email check during registration (Phase 3)
     *
     * Returns Optional<User> to avoid NullPointerException.
     * In Java 17+, always prefer Optional over returning null.
     */
    Optional<User> findByEmail(String email);

    /**
     * Checks if a user with the given email already exists.
     *
     * Spring generates: SELECT COUNT(*) FROM users WHERE email = ?
     * Returns true if count > 0.
     */
    boolean existsByEmail(String email);

}
